set system host-name GTE-03
set interfaces ge-0/0/0 description "uplink to PE-01 (AS65001)"
set interfaces ge-0/0/0 unit 0 family inet address 10.1.0.1/30
set interfaces ge-0/0/7 description "access port - office floor 3"
set interfaces ge-0/0/7 unit 0 family ethernet-switching interface-mode access vlan members v100
set interfaces ge-0/0/8 unit 0 family ethernet-switching interface-mode access vlan members v200
set vlans v100 vlan-id 100
set vlans v200 vlan-id 200
set protocols bgp group ebgp type external
set protocols bgp group ebgp neighbor 10.1.0.2 peer-as 65001
set routing-options autonomous-system 65000
